name: weather_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  dio: ^4.0.6
  build_runner: ^2.3.3
  flutter_bloc: ^8.1.1
  get_it: ^7.6.0
  dartz: ^0.10.1
  geolocator: ^9.0.2
  shared_preferences: ^2.1.2
  json_annotation: ^4.0.1
  json_serializable: ^6.1.3
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/snow.svg
    - assets/big_rain.svg
    - assets/rain_and_sun.svg
    - assets/rain.svg
    - assets/storm.svg
    - assets/sun.svg
    - assets/location.svg
  uses-material-design: true
